[project]
name = "collateral-utility"
authors = ["Developer"]
description = "Secure document management and collateralization smart contract"
telemetry = false
requirements = []
[contracts.collateral_utility]
path = "contracts/collateral_utility.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
